import React from 'react'
import Head from 'next/head'
import Layout1 from '../../../components/Layout1'

const Profile = () => {
    return (
        <>
            <Head>
                <title>Recipedia | User Profile</title>
                <meta name="description" content="Generated by Recipedia" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout1>
                <div>Profile Page</div>
            </Layout1>
        </>
    )
}

export default Profile