import Button from "../components/base/button/button"
import Input from "../components/base/input/input"
// import Navbar from "../components/module/navbar/navbar"
import Head from 'next/head'
import Layout1 from "../components/Layout1"
import AddRecipe from "./recipe/add"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Recipedia | Home</title>
        <meta name="description" content="Generated by Recipedia" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout1>
        <h1>Home Page</h1>
      </Layout1>
    </div>
  )
}

export default Home