import Button from "../components/base/button/button"
import Input from "../components/base/input/input"
import Navbar from "../components/module/navbar/navbar"
import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Recipedia</title>
        <meta name="description" content="Generated by Recipedia" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    </div>
  )
}

export default Home