// import Button from "../components/base/button/button"
// import Input from "../components/base/input/input"
// // import Navbar from "../components/module/navbar/navbar"
import Head from 'next/head'
import Layout1 from "../components/Layout1"
// import AddRecipe from "./recipe/add"

const LandingPage = () => {
  return (
    <>
      <Head>
        <title>Recipedia | Home</title>
        <meta name="description" content="Generated by Recipedia" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout1>
        <div>Landing</div>
      </Layout1>
    </>
  )
}

export default LandingPage